### PR TITLE
MTK Versioning

### PR DESCRIPTION
**Pull request by tnelson-doghouse**
-	Put mtk version into config
-	Set up renovatebot to update it

### CODE REVIEW

**Comment by tobybellwood** [comment]
The build will fail because the docker creds aren't passed to workflows that are triggered by a pull request from a fork.

**Comment by tnelson-doghouse** [comment]
OK.  So does this mean that the only way to test it is to merge it?  :p

**Comment by tnelson-doghouse** [comment]
(Note: this is all completely untested because I have no way of testing it).

**Comment by tobybellwood** [comment]
Made some updates and edits in https://github.com/uselagoon/database-image-task/compare/testing/fix-mtk-quoting-1?expand=1

**Comment by tnelson-doghouse** [comment]
That was impressively prompt :) .  That all looks good.  I'm new to renovatebot, so it was good to see what you've done with the Dockerfile updating.  

Do you need anything from me at this point?

**Comment by shreddedbacon** [comment]
Ping @tobybellwood for input on this one (or the separate branch)

**Pull request merged**
